# Question 3

# Implement Multilayer Perceptron(MLP), Convolutional Neural Network(CNN) as well as Support Vector Machines(SVM) to classify digits from the MNIST dataset.

# Importing Libraries

In [1]:
from mnist import MNIST
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Support Vector Machine


# Load dataset

In [0]:
mndata = MNIST('/content/data/')
xtrain, ytrain = mndata.load_training()
xtest, ytest = mndata.load_testing()
xtrain = np.array(xtrain)
ytrain = np.array(ytrain)
xtest = np.array(xtest)
ytest = np.array(ytest)

In [0]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler

# Normalizing the data between 0-254

In [0]:
svmxtrain = xtrain/255.0
svmytrain = ytrain
svmxtest = xtest/255.0
svmytest = ytest

# Applying standard scaler to transform the data such that its distribution will have a mean value 0 and standard deviation of 1.

In [0]:
scaler = StandardScaler()
svmxtrain = scaler.fit_transform(svmxtrain)
svmxtest = scaler.transform(svmxtest)

# Experiment 1:- Applying Support Vector Machine with Linear kernel and calculating the accuracy

In [0]:
svc1 = svm.SVC(kernel='linear')
svc1.fit(svmxtrain, svmytrain) 
y_predict1 = svc1.predict(svmxtest)
acc1 = accuracy_score(svmytest, y_predict1)
print('Accuracy = ',acc1)

Accuracy =  0.9293


# Confusion Matrix

In [0]:
print(confusion_matrix(svmytest, y_predict1))

[[ 951    0    5    2    2    8    8    2    1    1]
 [   0 1119    6    2    0    1    2    1    4    0]
 [  10   13  956   11    7    4    5    6   18    2]
 [   7    1   15  941    0   16    1    6   19    4]
 [   3    2   18    1  929    0    3    5    4   17]
 [   7    6    7   41    6  789   12    2   19    3]
 [  12    3   13    1    8   17  902    0    2    0]
 [   2    8   23   13   10    1    0  945    5   21]
 [  12    6   11   28    8   24    9    6  858   12]
 [   6    7    6   10   36    4    1   23   13  903]]


# Classification Report

In [0]:
print(classification_report(svmytest, y_predict1))

              precision    recall  f1-score   support

           0       0.94      0.97      0.96       980
           1       0.96      0.99      0.97      1135
           2       0.90      0.93      0.91      1032
           3       0.90      0.93      0.91      1010
           4       0.92      0.95      0.93       982
           5       0.91      0.88      0.90       892
           6       0.96      0.94      0.95       958
           7       0.95      0.92      0.93      1028
           8       0.91      0.88      0.90       974
           9       0.94      0.89      0.92      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000



# Experiment 2:- Applying Support Vector Machine with polynomial kernel and calculating the accuracy.

In [0]:
svc2 = svm.SVC(kernel='poly')
svc2.fit(svmxtrain, svmytrain) 
y_predict2 = svc2.predict(svmxtest)
acc2 = accuracy_score(svmytest, y_predict2)
print('Accuracy = ',acc2)

Accuracy =  0.9611


# Confusion Matrix

In [0]:
print(confusion_matrix(svmytest, y_predict2))

[[ 962    0    0    1    0    3    4    0   10    0]
 [   0 1122    3    0    2    1    4    0    3    0]
 [   6    0  973    3    3    1    2    7   37    0]
 [   0    0    1  971    1    3    2    5   22    5]
 [   0    0    2    0  955    0    6    2    4   13]
 [   2    1    3    3    2  863    6    1    9    2]
 [   5    3    1    0    8    8  919    0   14    0]
 [   1    8   11    2   12    0    0  958   11   25]
 [   1    0    3    6    5    8    1    3  943    4]
 [   3    4    1   11   24    3    0    4   14  945]]


# Classification Report

In [0]:
print(classification_report(svmytest, y_predict2))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.94      0.96      1032
           3       0.97      0.96      0.97      1010
           4       0.94      0.97      0.96       982
           5       0.97      0.97      0.97       892
           6       0.97      0.96      0.97       958
           7       0.98      0.93      0.95      1028
           8       0.88      0.97      0.92       974
           9       0.95      0.94      0.94      1009

    accuracy                           0.96     10000
   macro avg       0.96      0.96      0.96     10000
weighted avg       0.96      0.96      0.96     10000



# Experiment 3:- Applying Support Vector Machine with RBF kernel and calculating the accuracy

In [0]:
svc3 = svm.SVC(kernel='rbf')
svc3.fit(svmxtrain, svmytrain) 
y_predict3 = svc3.predict(svmxtest)
acc3 = accuracy_score(svmytest, y_predict3)
print('Accuracy = ',acc3)

Accuracy =  0.9661


# Confusion Matrix

In [0]:
print(confusion_matrix(svmytest, y_predict3))

[[ 968    0    1    1    0    3    3    2    2    0]
 [   0 1127    3    0    0    1    2    0    2    0]
 [   5    1  996    2    2    0    1   15    9    1]
 [   0    0    4  980    1    7    0   11    7    0]
 [   0    0   12    0  944    2    4    7    3   10]
 [   2    0    1   10    2  854    6    8    7    2]
 [   6    2    1    0    4    8  930    2    5    0]
 [   1    6   13    2    3    0    0  990    0   13]
 [   3    0    4    6    6    9    3   14  926    3]
 [   4    6    5   11   12    2    0   20    3  946]]


# Classification Report

In [0]:
print(classification_report(svmytest, y_predict3))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.97      0.96      1032
           3       0.97      0.97      0.97      1010
           4       0.97      0.96      0.97       982
           5       0.96      0.96      0.96       892
           6       0.98      0.97      0.98       958
           7       0.93      0.96      0.94      1028
           8       0.96      0.95      0.96       974
           9       0.97      0.94      0.95      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



# Multi-Layer Perceptron

In [0]:
from torchvision import datasets, transforms
import torch
import torchvision
from torch import nn
from torch import optim
from mnist import MNIST
import numpy as np
from torch.utils.data import TensorDataset
from torch import Tensor

# Loading the training dataset and test dataset and reshaping it to the length of the dataset * 28 * 28 * 1 to feed into the multi layer perceptron and normalizing it between 0-254 and creating batches of size 64

In [0]:
mndata = MNIST('/content/data/')
xtrain, ytrain = mndata.load_training()
xtest, ytest = mndata.load_testing()
original = np.array(ytest)
xtrain = np.array(xtrain)
ytrain = np.array(ytrain)
xtest = np.array(xtest)
ytest = np.array(ytest)
xtrain = xtrain.reshape(xtrain.shape[0], 28, 28, 1)
xtest = xtest.reshape(xtest.shape[0], 28, 28, 1)
xtrain = xtrain.astype('float')
xtest = xtest.astype('float')
xtrain = xtrain/255
xtest = xtest/255

In [0]:
xtrain = Tensor(xtrain)
ytrain = Tensor(ytrain)
ytrain = ytrain.long()
xtest = Tensor(xtest)
ytest = Tensor(ytest)
trainset = TensorDataset(xtrain,ytrain)
testset = TensorDataset(xtest, ytest)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=True)

# Experiment 4:- Multi layer perceptron of input layer consisting of 784(28 * 28) neurons, two hidden layers with 128 neurons and 64 neurons in each layer correspondingly. Output layers of 10 neurons for 10 classes. Applying ReLu(y = max(0, x)) activation function in both of the hidden layers. Linear activation function (A = cx) is used in output layer.

In [0]:
inputlayer = 784
hiddenlayer = [128, 64]
outputlayer = 10

model = nn.Sequential(nn.Linear(inputlayer, hiddenlayer[0]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[0], hiddenlayer[1]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[1], outputlayer))

# The loss function is Cross Entropy loss (H(P, Q) = – sum x in X P(x) * log(Q(x)) ) and Stochastic Gradient descent optimzer is used with learning rate 0.003 and momentum 0.9. Epochs is 100.

In [0]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.003, momentum=0.9)
epochs = 100
for e in range(epochs):
    total_loss = 0
    for xtrain, ytrain in trainloader:
        xtrain = xtrain.view(xtrain.shape[0], -1)        
        optimizer.zero_grad()        
        result = model(xtrain)
        loss = criterion(result, ytrain)       
        loss.backward()
        optimizer.step()       
        total_loss += loss.item()

# Prediction of the test data and calculating accuracy

In [0]:
correct_prediction, total_count = 0, 0
original1 = []
predictions1 =[]
for xtest,ytest in testloader:
    for i in range(len(ytest)):
        img = xtest[i].view(1, 784)
        with torch.no_grad():
            ps = model(img)
        probab = list(ps.numpy()[0])
        prediction = probab.index(max(probab))
        real = ytest.numpy()[i]
        original1.append(real)
        predictions1.append(prediction)
        if(real == prediction):
            correct_prediction += 1
        total_count += 1
print("\nModel Accuracy =", (correct_prediction/total_count))


Model Accuracy = 0.9793


# Confusion Matrix

In [0]:
print(confusion_matrix(original1, predictions1))

[[ 969    1    1    1    1    0    3    1    2    1]
 [   0 1125    3    1    0    1    2    1    2    0]
 [   4    2 1007    6    3    0    1    4    5    0]
 [   0    0    3  992    0    3    0    4    4    4]
 [   1    0    2    1  960    0    4    3    1   10]
 [   3    0    0   10    2  866    4    1    3    3]
 [   3    2    2    1    4    3  941    0    2    0]
 [   0    3    7    1    0    0    0 1011    1    5]
 [   5    0    3    8    3    3    3    4  940    5]
 [   2    2    0    4    7    4    1    3    4  982]]


# Classification Report

In [0]:
print(classification_report(original1, predictions1))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.99       980
         1.0       0.99      0.99      0.99      1135
         2.0       0.98      0.98      0.98      1032
         3.0       0.97      0.98      0.97      1010
         4.0       0.98      0.98      0.98       982
         5.0       0.98      0.97      0.98       892
         6.0       0.98      0.98      0.98       958
         7.0       0.98      0.98      0.98      1028
         8.0       0.98      0.97      0.97       974
         9.0       0.97      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



# Experiment 5:- Multi layer perceptron of input layer consisting of 784(28 * 28) neurons, three hidden layers with 128 neurons and 64 neurons and 32 in each layer correspondingly. Output layers of 10 neurons for 10 classes. Applying ReLu(y = max(0, x)) activation function in all of the hidden layers. Linear activation function (A = cx) is used in output layer.

In [0]:
inputlayer = 784
hiddenlayer = [128, 64, 32]
outputlayer = 10

model2 = nn.Sequential(nn.Linear(inputlayer, hiddenlayer[0]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[0], hiddenlayer[1]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[1], hiddenlayer[2]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[2], outputlayer))

# The loss function is Cross Entropy loss (H(P, Q) = – sum x in X P(x) * log(Q(x)) ) and Stochastic Gradient descent optimzer is used with learning rate 0.003 and momentum 0.9. Epochs is 100.

In [0]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model2.parameters(), lr=0.003, momentum=0.9)
epochs = 100
for e in range(epochs):
    total_loss = 0
    for xtrain, ytrain in trainloader:
        xtrain = xtrain.view(xtrain.shape[0], -1)        
        optimizer.zero_grad()        
        result = model2(xtrain)
        loss = criterion(result, ytrain)       
        loss.backward()
        optimizer.step()       
        total_loss += loss.item()

# Prediction of the test data and calculating accuracy

In [0]:
correct_prediction, total_count = 0, 0
original2 = []
predictions2 = []
for xtest,ytest in testloader:
    for i in range(len(ytest)):
        img = xtest[i].view(1, 784)
        with torch.no_grad():
            ps = model2(img)
        probab = list(ps.numpy()[0])
        prediction = probab.index(max(probab))
        real = ytest.numpy()[i]
        original2.append(real)
        predictions2.append(prediction)
        if(real == prediction):
            correct_prediction += 1
        total_count += 1
print("\nModel Accuracy =", (correct_prediction/total_count))


Model Accuracy = 0.9775


# Consusion Matrix

In [0]:
print(confusion_matrix(original2, predictions2))

[[ 971    0    1    0    0    1    3    1    2    1]
 [   0 1128    2    0    0    0    2    1    2    0]
 [   6    3 1002    5    2    0    3    5    6    0]
 [   0    0    3  987    0    4    0    7    5    4]
 [   1    0    2    1  960    0    4    3    0   11]
 [   2    0    0   11    1  865    4    2    4    3]
 [   4    3    5    1    5    6  933    0    1    0]
 [   2    7    4    5    1    0    1  999    3    6]
 [   5    1    3    5    3    3    1    2  947    4]
 [   3    3    0    3    9    4    0    2    2  983]]


# Classification Report

In [0]:
print(classification_report(original2, predictions2))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98       980
         1.0       0.99      0.99      0.99      1135
         2.0       0.98      0.97      0.98      1032
         3.0       0.97      0.98      0.97      1010
         4.0       0.98      0.98      0.98       982
         5.0       0.98      0.97      0.97       892
         6.0       0.98      0.97      0.98       958
         7.0       0.98      0.97      0.97      1028
         8.0       0.97      0.97      0.97       974
         9.0       0.97      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



# Experiment 6:- Multi layer perceptron of input layer consisting of 784(28 * 28) neurons, three hidden layers with 128 neurons and 64 neurons and 32 in each layer correspondingly. Output layers of 10 neurons for 10 classes. Applying sigmoid(y = 1/(1+e^(-x)) activation function in all of the hidden layers. Linear activation function (A = cx) is used in output layer.


In [0]:
inputlayer = 784
hiddenlayer = [128, 64, 32]
outputlayer = 10

model3 = nn.Sequential(nn.Linear(inputlayer, hiddenlayer[0]),
                      nn.Sigmoid(),
                      nn.Linear(hiddenlayer[0], hiddenlayer[1]),
                      nn.Sigmoid(),
                      nn.Linear(hiddenlayer[1], hiddenlayer[2]),
                      nn.Sigmoid(),
                      nn.Linear(hiddenlayer[2], outputlayer))

# The loss function is Cross Entropy loss (H(P, Q) = – sum x in X P(x) * log(Q(x)) ) and Stochastic Gradient descent optimzer is used with learning rate 0.003 and momentum 0.9. Epochs is 100.


In [0]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model3.parameters(), lr=0.003, momentum=0.9)
epochs = 100
for e in range(epochs):
    total_loss = 0
    for xtrain, ytrain in trainloader:
        xtrain = xtrain.view(xtrain.shape[0], -1)        
        optimizer.zero_grad()        
        result = model3(xtrain)
        loss = criterion(result, ytrain)       
        loss.backward()
        optimizer.step()       
        total_loss += loss.item()

# Prediction of the test data and calculating accuracy

In [0]:
correct_prediction, total_count = 0, 0
original3 = []
predictions3 = []
for xtest,ytest in testloader:
    for i in range(len(ytest)):
        img = xtest[i].view(1, 784)
        with torch.no_grad():
            ps = model3(img)
        probab = list(ps.numpy()[0])
        prediction = probab.index(max(probab))
        real = ytest.numpy()[i]
        original3.append(real)
        predictions3.append(prediction)
        if(real == prediction):
            correct_prediction += 1
        total_count += 1
print("\nModel Accuracy =", (correct_prediction/total_count))


Model Accuracy = 0.9673


# Confusion Matrix

In [0]:
print(confusion_matrix(original3, predictions3))

[[ 966    0    4    0    1    5    1    1    2    0]
 [   0 1121    2    5    0    1    0    2    4    0]
 [   4    5  999    8    1    0    2    9    4    0]
 [   0    1    3  986    0    7    0    7    5    1]
 [   4    0    2    0  943    0    6    6    1   20]
 [   5    0    1   25    1  846    1    0   10    3]
 [  11    2    6    0    8    5  922    0    4    0]
 [   1   10    6    6    1    0    0  996    0    8]
 [   1    3    4    8    4   11    3    4  932    4]
 [   3    3    0    6    8    9    1   16    1  962]]


# Classification Report

In [0]:
print(classification_report(original3, predictions3))

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98       980
         1.0       0.98      0.99      0.98      1135
         2.0       0.97      0.97      0.97      1032
         3.0       0.94      0.98      0.96      1010
         4.0       0.98      0.96      0.97       982
         5.0       0.96      0.95      0.95       892
         6.0       0.99      0.96      0.97       958
         7.0       0.96      0.97      0.96      1028
         8.0       0.97      0.96      0.96       974
         9.0       0.96      0.95      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



# Experiment 7:- Multi layer perceptron of input layer consisting of 784(28 * 28) neurons, three hidden layers with 128 neurons and 64 neurons and 32 in each layer correspondingly. Output layers of 10 neurons for 10 classes. Applying ReLu(y = max(a,0)) in the first two hidden layers. Applying sigmoid(y = 1/(1+e^(-x)) activation function in the third hidden layer. Linear activation function (A = cx) is used in output layer.

In [0]:
inputlayer = 784
hiddenlayer = [128, 64,32]
outputlayer = 10

model5 = nn.Sequential(nn.Linear(inputlayer, hiddenlayer[0]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[0], hiddenlayer[1]),
                      nn.ReLU(),
                      nn.Linear(hiddenlayer[1], hiddenlayer[2]),
                      nn.Sigmoid(),
                      nn.Linear(hiddenlayer[2], outputlayer))

# The loss function is Cross Entropy loss (H(P, Q) = – sum x in X P(x) * log(Q(x)) ) and Stochastic Gradient descent optimzer is used with learning rate 0.003 and momentum 0.9. Epoch is 100.

In [0]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model5.parameters(), lr=0.003, momentum=0.9)
epochs = 100
for e in range(epochs):
    total_loss = 0
    for xtrain, ytrain in trainloader:
        xtrain = xtrain.view(xtrain.shape[0], -1)        
        optimizer.zero_grad()        
        result = model5(xtrain)
        loss = criterion(result, ytrain)       
        loss.backward()
        optimizer.step()       
        total_loss += loss.item()

# Prediction of the test data and calculating accuracy

In [0]:
correct_prediction, total_count = 0, 0
predictions5 = []
original5 = []
for xtest,ytest in testloader:
    for i in range(len(ytest)):
        img = xtest[i].view(1, 784)
        with torch.no_grad():
            ps = model5(img)
        probab = list(ps.numpy()[0])
        prediction = probab.index(max(probab))
        real = ytest.numpy()[i]
        original5.append(real)
        predictions5.append(prediction)
        if(real == prediction):
            correct_prediction += 1
        total_count += 1
print("\nModel Accuracy =", (correct_prediction/total_count))


Model Accuracy = 0.977


# Confusion Matrix.

In [0]:
print(confusion_matrix(original5,predictions5))

[[ 969    0    2    1    1    2    2    1    1    1]
 [   0 1125    3    0    0    1    3    1    2    0]
 [   2    1 1010    7    1    0    3    4    4    0]
 [   0    0    4  986    0   10    0    4    4    2]
 [   0    1    4    0  955    0    6    2    2   12]
 [   4    0    0   10    1  861    6    1    4    5]
 [   6    3    0    1    5    4  937    0    2    0]
 [   1    6    5    3    2    0    0 1000    2    9]
 [   2    0    3    6    6    6    3    1  942    5]
 [   4    2    0    2    7    3    0    3    3  985]]


# Classification Report

In [0]:
print(classification_report(original5, predictions5))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98       980
         1.0       0.99      0.99      0.99      1135
         2.0       0.98      0.98      0.98      1032
         3.0       0.97      0.98      0.97      1010
         4.0       0.98      0.97      0.97       982
         5.0       0.97      0.97      0.97       892
         6.0       0.98      0.98      0.98       958
         7.0       0.98      0.97      0.98      1028
         8.0       0.98      0.97      0.97       974
         9.0       0.97      0.98      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



# Experiment 7:- Multi layer perceptron of input layer consisting of 784(28 * 28) neurons, three hidden layers with 128 neurons and 64 neurons and 32 in each layer correspondingly. Output layers of 10 neurons for 10 classes. Applying Tanh(f(x) = 1 — exp(-2x) / 1 + exp(-2x)) in the first two hidden layers. Applying sigmoid(y = 1/(1+e^(-x)) activation function in the third hidden layer. Linear activation function (A = cx) is used in output layer.

In [0]:
inputlayer = 784
hiddenlayer = [128, 64,32]
outputlayer = 10

model6 = nn.Sequential(nn.Linear(inputlayer, hiddenlayer[0]),
                      nn.Tanh(),
                      nn.Linear(hiddenlayer[0], hiddenlayer[1]),
                      nn.Tanh(),
                      nn.Linear(hiddenlayer[1], hiddenlayer[2]),
                      nn.Sigmoid(),
                      nn.Linear(hiddenlayer[2], outputlayer))

# The loss function is Cross Entropy loss (H(P, Q) = – sum x in X P(x) * log(Q(x)) ) and Stochastic Gradient descent optimzer is used with learning rate 0.003 and momentum 0.9. Epoch is 100.

In [0]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model6.parameters(), lr=0.003, momentum=0.9)
epochs = 100
for e in range(epochs):
    total_loss = 0
    for xtrain, ytrain in trainloader:
        xtrain = xtrain.view(xtrain.shape[0], -1)        
        optimizer.zero_grad()        
        result = model6(xtrain)
        loss = criterion(result, ytrain)       
        loss.backward()
        optimizer.step()       
        total_loss += loss.item()

# Prediction of the test data and calculating accuracy

In [0]:
correct_prediction, total_count = 0, 0
predictions6 = []
original6 = []
for xtest,ytest in testloader:
    for i in range(len(ytest)):
        img = xtest[i].view(1, 784)
        with torch.no_grad():
            ps = model6(img)
        probab = list(ps.numpy()[0])
        prediction = probab.index(max(probab))
        real = ytest.numpy()[i]
        original6.append(real)
        predictions6.append(prediction)
        if(real == prediction):
            correct_prediction += 1
        total_count += 1
print("\nModel Accuracy =", (correct_prediction/total_count))


Model Accuracy = 0.9772


# Confusion Matrix

In [0]:
print(confusion_matrix(original6,predictions6))

[[ 966    0    2    0    1    3    2    1    3    2]
 [   0 1127    2    1    0    0    1    1    3    0]
 [   3    3 1010    5    1    0    1    3    6    0]
 [   0    0    4  986    0    5    0    3   10    2]
 [   1    1    1    0  960    1    6    1    1   10]
 [   4    0    0    9    1  863    2    3    6    4]
 [   5    2    3    0    3    4  939    0    2    0]
 [   0    4    9    3    1    1    0  998    1   11]
 [   4    1    4    4    2    6    2    2  946    3]
 [   0    2    0    4   10    2    1    9    4  977]]


# Classification Report

In [0]:
print(classification_report(original6, predictions6))

              precision    recall  f1-score   support

         0.0       0.98      0.99      0.98       980
         1.0       0.99      0.99      0.99      1135
         2.0       0.98      0.98      0.98      1032
         3.0       0.97      0.98      0.98      1010
         4.0       0.98      0.98      0.98       982
         5.0       0.98      0.97      0.97       892
         6.0       0.98      0.98      0.98       958
         7.0       0.98      0.97      0.97      1028
         8.0       0.96      0.97      0.97       974
         9.0       0.97      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



# Convolution Neural Network

In [3]:
# from torchvision import datasets, transforms
# import torch
# import torchvision
# from torch import nn
# from torch import optim
from mnist import MNIST
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
from keras.optimizers import SGD
import keras
from keras.layers.advanced_activations import LeakyReLU

Using TensorFlow backend.


# Loading the training dataset and test dataset and reshaping it to the length of the dataset * 28 * 28 * 1 to feed into the multi layer perceptron and normalizing it between 0-254.

In [4]:
mndata = MNIST('G:\second_sem\SMAI\Assignment_3\q3\dataset')
xtrain, ytrain = mndata.load_training()
xtest, ytest = mndata.load_testing()
xtrain = np.array(xtrain)
ytrain = keras.utils.to_categorical(ytrain, 10)
xtest = np.array(xtest)
original = np.array(ytest)
ytest = keras.utils.to_categorical(ytest, 10)
xtrain = xtrain.reshape(xtrain.shape[0], 28, 28, 1)
xtest = xtest.reshape(xtest.shape[0], 28, 28, 1)
xtrain = xtrain.astype('float')
xtest = xtest.astype('float')
xtrain = xtrain/255
xtest = xtest/255

# Experiment 8:- The model is comprised of one output layer and one 2d convolution layer and one hidden layer. On the hidden layer and 2d convolution layer ReLu activation function has been used. Softmax activation function is used in output layer. 2D convolution layer creates a convolution kernel that is convolved with the layer input to produce a tensor of outputs. The number of output filters in the convolution is 32. Kernel of size 3x3 is used. After that max pooling of 2x2 matrix is used. The dropout rate is set to 30% from convolution layer to the hidden layer, meaning one in  almost 3 inputs will be randomly excluded from each update cycle. The convoltuion layer to hidden layer is densed and 128 neurons is used in the hidden layer. From the hidden layer to output layer dropout rate is set 25% meaning one in 4 inputs will be discarded randomly and it is densed. 10 neuronse for 10 classes is used in output layer. Stochastic gradient descent optimizer is used with learning rate 0.003 and momentum 0.9. The loss funtion is used cross entropy loss. And the metrics for the model is "accuracy". Batch size of 64 is created with epochs is set 10.

In [14]:
model1 = Sequential()
model1.add(Conv2D(filters=32, kernel_size=(3, 3), activation='relu',input_shape=(28,28,1)))
model1.add(MaxPooling2D(pool_size=(2, 2)))
model1.add(Dropout(0.30))
model1.add(Flatten())
model1.add(Dense(units=128, activation='relu'))
model1.add(Dropout(0.25))
model1.add(Dense(units=10, activation='softmax'))
optimizer = SGD(lr=0.003, momentum=0.9)
model1.compile(loss=keras.losses.categorical_crossentropy,optimizer=optimizer, metrics=['accuracy'])
model1.fit(x=xtrain,y=ytrain,batch_size=64,epochs=10)
acc1 = model1.evaluate(xtest, ytest)
acc1

Epoch 1/10
60000/60000 [==============================] - 33s 558us/step - loss: 0.5601 - acc: 0.8288
Epoch 2/10
60000/60000 [==============================] - 33s 551us/step - loss: 0.2524 - acc: 0.9228
Epoch 3/10
60000/60000 [==============================] - 33s 551us/step - loss: 0.1992 - acc: 0.9394
Epoch 4/10
60000/60000 [==============================] - 33s 553us/step - loss: 0.1717 - acc: 0.9481
Epoch 5/10
60000/60000 [==============================] - 33s 547us/step - loss: 0.1505 - acc: 0.9541
Epoch 6/10
60000/60000 [==============================] - 33s 548us/step - loss: 0.1393 - acc: 0.9569
Epoch 7/10
60000/60000 [==============================] - 34s 567us/step - loss: 0.1261 - acc: 0.9617
Epoch 8/10
60000/60000 [==============================] - 33s 551us/step - loss: 0.1156 - acc: 0.9644
Epoch 9/10
60000/60000 [==============================] - 33s 549us/step - loss: 0.1059 - acc: 0.9673
Epoch 10/10
10000/10000 [==============================] - 2s 228us/step


[0.0648645735614933, 0.9797]

# Prediction of the digit.

In [0]:
temp1 = model1.predict(xtest)
pred1 = np.argmax(np.round(temp1),axis=1)

# Confusion Matrix

In [0]:
print(confusion_matrix(original,pred1))

[[ 976    0    0    0    0    0    0    1    3    0]
 [   2 1124    2    1    0    0    2    0    4    0]
 [  13    0 1007    1    1    0    0    4    6    0]
 [   3    0    1  994    0    1    0    4    7    0]
 [   7    0    6    0  941    0    1    1    2   24]
 [  10    0    0   10    0  863    2    1    5    1]
 [  11    3    1    1    4    4  931    0    3    0]
 [  14    7   10    1    0    0    0  984    3    9]
 [   9    0    2    5    0    2    0    2  952    2]
 [  11    5    0    7    6    2    0    4    2  972]]


# Classification Report

In [0]:
print(classification_report(original,pred1))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.98      0.98      1032
           3       0.97      0.98      0.98      1010
           4       0.99      0.96      0.97       982
           5       0.99      0.97      0.98       892
           6       0.99      0.97      0.98       958
           7       0.98      0.96      0.97      1028
           8       0.96      0.98      0.97       974
           9       0.96      0.96      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



# Experiment 9:- The model is comprised of one output layer and one 2d convolution layer and one hidden layer. On the hidden layer and 2d convolution layer ReLu activation function has been used. Softmax activation function is used in output layer. 2D convolution layer creates a convolution kernel that is convolved with the layer input to produce a tensor of outputs. The number of output filters in the convolution is 64. Kernel of size 4x4 is used. After that max pooling of 2x2 matrix is used. The dropout rate is set to 50% from convolution layer to the hidden layer, meaning one in 2 inputs will be randomly excluded from each update cycle. The convoltuion layer to hidden layer is densed and 128 neurons is used in the hidden layer. From the hidden layer to output layer dropout rate is set 20% meaning one in 5 inputs will be discarded randoml and it is densed. 10 neuronse for 10 classes is used in output layer. Stochastic gradient descent optimizer is used with learning rate 0.003 and momentum 0.9. The loss funtion is used cross entropy loss. And the metrics for the model is "accuracy". Batch size of 64 is created with epochs is set 10.

In [0]:
model2 = Sequential()
model2.add(Conv2D(filters=64, kernel_size=(4, 4), activation='relu',input_shape=(28,28,1)))
model2.add(MaxPooling2D(pool_size=(2, 2)))
model2.add(Dropout(0.5))
model2.add(Flatten())
model2.add(Dense(units=128, activation='relu'))
model2.add(Dropout(0.2))
model2.add(Dense(units=10, activation='softmax'))
optimizer = SGD(lr=0.003, momentum=0.9)
model2.compile(loss=keras.losses.categorical_crossentropy,optimizer=optimizer, metrics=['accuracy'])
model2.fit(x=xtrain,y=ytrain,batch_size=64,epochs=10)
acc2 = model2.evaluate(xtest, ytest)
acc2

Epoch 1/10
60000/60000 [==============================] - 50s 840us/step - loss: 0.5143 - acc: 0.8440
Epoch 2/10
60000/60000 [==============================] - 51s 849us/step - loss: 0.2270 - acc: 0.9303
Epoch 3/10
60000/60000 [==============================] - 50s 831us/step - loss: 0.1683 - acc: 0.9492
Epoch 4/10
60000/60000 [==============================] - 50s 827us/step - loss: 0.1356 - acc: 0.9594
Epoch 5/10
60000/60000 [==============================] - 50s 828us/step - loss: 0.1162 - acc: 0.9651
Epoch 6/10
60000/60000 [==============================] - 50s 833us/step - loss: 0.1025 - acc: 0.9696
Epoch 7/10
60000/60000 [==============================] - 50s 828us/step - loss: 0.0926 - acc: 0.9719
Epoch 8/10
60000/60000 [==============================] - 50s 827us/step - loss: 0.0838 - acc: 0.9740
Epoch 9/10
60000/60000 [==============================] - 51s 846us/step - loss: 0.0760 - acc: 0.9769
Epoch 10/10
10000/10000 [==============================] - 2s 241us/step


[0.04387621255386621, 0.9851]

# Prediction of the digits

In [0]:
temp2 = model2.predict(xtest)
pred2 = np.argmax(np.round(temp2),axis=1)

# Confusion Matrix

In [0]:
print(confusion_matrix(original,pred2))

[[ 977    0    0    0    0    0    0    1    2    0]
 [   3 1126    2    1    0    0    1    0    2    0]
 [   7    1 1014    0    2    0    0    6    2    0]
 [   3    0    3  997    0    2    0    2    3    0]
 [   6    0    1    0  972    0    0    0    1    2]
 [   2    0    0    4    0  880    3    1    1    1]
 [  11    3    0    1    3    3  937    0    0    0]
 [   5    1    7    1    0    0    0 1010    1    3]
 [   7    1    2    3    1    2    1    3  950    4]
 [  13    5    0    1    9    0    0    4    1  976]]


# Classification Report

In [0]:
print(classification_report(original,pred2))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       980
           1       0.99      0.99      0.99      1135
           2       0.99      0.98      0.98      1032
           3       0.99      0.99      0.99      1010
           4       0.98      0.99      0.99       982
           5       0.99      0.99      0.99       892
           6       0.99      0.98      0.99       958
           7       0.98      0.98      0.98      1028
           8       0.99      0.98      0.98       974
           9       0.99      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000



# Experiment 10:- The model is comprised of one output layer and one 2d convolution layer and one hidden layer. On the hidden layer and 2d convolution layer ReLu activation function has been used. Softmax activation function is used in output layer. 2D convolution layer creates a convolution kernel that is convolved with the layer input to produce a tensor of outputs. The number of output filters in the convolution is 32. Kernel of size 3x3 is used. After that max pooling of 2x2 matrix is used. The dropout rate is set to 20% from convolution layer to the hidden layer, meaning one in 5 inputs will be randomly excluded from each update cycle. The convoltuion layer to hidden layer is densed and 64 neurons is used in the hidden layer. From the hidden layer to output layer dropout rate is set 10% meaning one in 10 inputs will be discarded randoml and it is densed. 10 neuronse for 10 classes is used in output layer. Stochastic gradient descent optimizer is used with learning rate 0.003 and momentum 0.9. The loss funtion is used cross entropy loss. And the metrics for the model is "accuracy". Batch size of 64 is created with epochs is set 10.


In [0]:
model3 = Sequential()
model3.add(Conv2D(filters=32, kernel_size=(3, 3), activation='relu',input_shape=(28,28,1)))
model3.add(MaxPooling2D(pool_size=(2, 2)))
model3.add(LeakyReLU(alpha=0.2))
model3.add(Flatten())
model3.add(Dense(units=64, activation='relu'))
model3.add(LeakyReLU(alpha=0.1))
model3.add(Dense(units=10, activation='softmax'))
optimizer = SGD(lr=0.003, momentum=0.9)
model3.compile(loss=keras.losses.categorical_crossentropy,optimizer=optimizer, metrics=['accuracy'])
model3.fit(x=xtrain,y=ytrain,batch_size=64,epochs=10)
acc3 = model3.evaluate(xtest, ytest)
acc3

Epoch 1/10
60000/60000 [==============================] - 24s 404us/step - loss: 0.4256 - acc: 0.8799
Epoch 2/10
60000/60000 [==============================] - 24s 397us/step - loss: 0.1935 - acc: 0.9422
Epoch 3/10
60000/60000 [==============================] - 24s 397us/step - loss: 0.1447 - acc: 0.9569
Epoch 4/10
60000/60000 [==============================] - 24s 397us/step - loss: 0.1170 - acc: 0.9649
Epoch 5/10
60000/60000 [==============================] - 24s 393us/step - loss: 0.0977 - acc: 0.9703
Epoch 6/10
60000/60000 [==============================] - 23s 391us/step - loss: 0.0842 - acc: 0.9743
Epoch 7/10
60000/60000 [==============================] - 23s 390us/step - loss: 0.0745 - acc: 0.9776
Epoch 8/10
60000/60000 [==============================] - 24s 398us/step - loss: 0.0654 - acc: 0.9804
Epoch 9/10
60000/60000 [==============================] - 24s 399us/step - loss: 0.0593 - acc: 0.9822
Epoch 10/10
10000/10000 [==============================] - 2s 208us/step


[0.07566864336489235, 0.9758]

# Prediction of the digits

In [0]:
temp3 = model3.predict(xtest)
pred3 = np.argmax(np.round(temp3),axis=1)

# Consfusion Matrix

In [0]:
print(confusion_matrix(original,pred3))

[[ 974    0    1    0    0    0    1    1    3    0]
 [   2 1123    4    0    0    1    4    0    1    0]
 [   7    0 1009    1    2    0    1    3    9    0]
 [   7    0    9  980    0    0    0    3    7    4]
 [   2    0    4    0  973    0    1    0    1    1]
 [  12    0    0    9    1  855    4    1    9    1]
 [  14    2    0    1    3    2  933    0    3    0]
 [   5    6   14    1    0    0    0  996    3    3]
 [  10    0    1    2    3    0    1    1  956    0]
 [  21    6    1    7   16    2    0    9    7  940]]


# Classification Report

In [0]:
print(classification_report(original,pred3))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.97      1032
           3       0.98      0.97      0.97      1010
           4       0.97      0.99      0.98       982
           5       0.99      0.96      0.98       892
           6       0.99      0.97      0.98       958
           7       0.98      0.97      0.98      1028
           8       0.96      0.98      0.97       974
           9       0.99      0.93      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



# Experiment 11:- The model is comprised of one output layer and one 2d convolution layer and one hidden layer. On the hidden layer and 2d convolution layer Tanh activation function has been used. Softmax activation function is used in output layer. 2D convolution layer creates a convolution kernel that is convolved with the layer input to produce a tensor of outputs. The number of output filters in the convolution is 64. Kernel of size 2x2 is used. After that max pooling of 2x2 matrix is used. The dropout rate is set to 30% from convolution layer to the hidden layer, meaning one in almost 3 inputs will be randomly excluded from each update cycle. The convoltuion layer to hidden layer is densed and 128 neurons is used in the hidden layer. From the hidden layer to output layer dropout rate is set 20% meaning one in 5 inputs will be discarded randoml and it is densed. 10 neuronse for 10 classes is used in output layer. Stochastic gradient descent optimizer is used with learning rate 0.003 and momentum 0.9. The loss funtion is used cross entropy loss. And the metrics for the model is "accuracy". Batch size of 64 is created with epochs is set 10.


In [10]:
model4 = Sequential()
model4.add(Conv2D(filters=64, kernel_size=(2, 2), strides=(2, 2), activation='tanh',input_shape=(28,28,1)))
model4.add(MaxPooling2D(pool_size=(2, 2)))
model4.add(Dropout(0.3))
model4.add(Flatten())
model4.add(Dense(units=128, activation='tanh'))
model4.add(Dropout(0.2))
model4.add(Dense(units=10, activation='softmax'))
optimizer = SGD(lr=0.003, momentum=0.9)
model4.compile(loss=keras.losses.categorical_crossentropy,optimizer=optimizer, metrics=['accuracy'])
model4.fit(x=xtrain,y=ytrain,batch_size=64,epochs=10)
acc4 = model4.evaluate(xtest, ytest)
acc4

Epoch 1/10
60000/60000 [==============================] - 18s 301us/step - loss: 0.7211 - acc: 0.7884
Epoch 2/10
60000/60000 [==============================] - 18s 295us/step - loss: 0.4089 - acc: 0.8733
Epoch 3/10
60000/60000 [==============================] - 18s 296us/step - loss: 0.3310 - acc: 0.8982
Epoch 4/10
60000/60000 [==============================] - 18s 295us/step - loss: 0.2722 - acc: 0.9171
Epoch 5/10
60000/60000 [==============================] - 18s 299us/step - loss: 0.2326 - acc: 0.9295
Epoch 6/10
60000/60000 [==============================] - 18s 298us/step - loss: 0.2073 - acc: 0.9378
Epoch 7/10
60000/60000 [==============================] - 18s 294us/step - loss: 0.1897 - acc: 0.9422
Epoch 8/10
60000/60000 [==============================] - 18s 299us/step - loss: 0.1763 - acc: 0.9458
Epoch 9/10
60000/60000 [==============================] - 18s 298us/step - loss: 0.1664 - acc: 0.9489
Epoch 10/10
10000/10000 [==============================] - 1s 106us/step


[0.115869736199826, 0.964]

# Prediction of the digits

In [0]:
temp4 = model4.predict(xtest)
pred4 = np.argmax(np.round(temp4),axis=1)

# Confusion Matrix

In [12]:
print(confusion_matrix(original,pred4))

[[ 972    0    0    0    0    1    1    3    3    0]
 [   4 1122    3    0    0    1    3    1    1    0]
 [  24    2  981    5    4    0    3    5    7    1]
 [  10    0    3  980    0    5    1    5    4    2]
 [  11    1    2    0  935    0    8    4    3   18]
 [  26    1    1   15    0  836    8    2    3    0]
 [  13    2    1    0    2    8  931    0    1    0]
 [  25    4   15    2    1    0    0  965    1   15]
 [  23    0    6   10    4    2    2    3  920    4]
 [  28    2    1    7   10    4    0   13    1  943]]


# Classification Report

In [13]:
print(classification_report(original,pred4))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.95      0.96      1032
           3       0.96      0.97      0.97      1010
           4       0.98      0.95      0.96       982
           5       0.98      0.94      0.96       892
           6       0.97      0.97      0.97       958
           7       0.96      0.94      0.95      1028
           8       0.97      0.94      0.96       974
           9       0.96      0.93      0.95      1009

    accuracy                           0.96     10000
   macro avg       0.96      0.96      0.96     10000
weighted avg       0.96      0.96      0.96     10000



# Summary : The best performing model is as The model is comprised of one output layer and one 2d convolution layer and one hidden layer. On the hidden layer and 2d convolution layer ReLu activation function has been used. Softmax activation function is used in output layer. 2D convolution layer creates a convolution kernel that is convolved with the layer input to produce a tensor of outputs. The number of output filters in the convolution is 64. Kernel of size 4x4 is used. After that max pooling of 2x2 matrix is used. The dropout rate is set to 50% from convolution layer to the hidden layer, meaning one in 2 inputs will be randomly excluded from each update cycle. The convoltuion layer to hidden layer is densed and 128 neurons is used in the hidden layer. From the hidden layer to output layer dropout rate is set 20% meaning one in 5 inputs will be discarded randoml and it is densed. 10 neuronse for 10 classes is used in output layer. Stochastic gradient descent optimizer is used with learning rate 0.003 and momentum 0.9. The loss funtion is used cross entropy loss. And the metrics for the model is "accuracy". Batch size of 64 is created with epochs is set 10.